---
- import_playbook: playbooks/common.yml
- import_playbook: playbooks/public.yml
- import_playbook: playbooks/internal.yml
- import_playbook: playbooks/connect.yml
- import_playbook: playbooks/dns.yml
- import_playbook: playbooks/immich.yml
- import_playbook: playbooks/immich_backup.yml
- import_playbook: playbooks/developer.yml
