---
- import_playbook: playbooks/common.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/public.yml
- import_playbook: playbooks/internal.yml
- import_playbook: playbooks/connect.yml
- import_playbook: playbooks/dns.yml
