---
all:
  hosts:
    tbeelink:
      ansible_connection: local
    tonypi:
      ansible_host: 192.168.1.83
    chadpi:
      ansible_host: 127.0.0.1
      ansible_port: 9005
  children:
    common:
      hosts:
        tbeelink:
        tonypi:
        chadpi:
    internal:
      hosts:
        tonypi:
    docker:
      hosts:
        tonypi:
        tbeelink:
    public:
      hosts:
        tbeelink:
    immich:
      hosts:
        tbeelink:
    immich_backup:
      hosts:
        chadpi:
    connect:
      hosts:
        chadpi:
          listen_port: 9005
          enabled: true
    dns:
      hosts:
        tbeelink:
          dns_records:
            - { dns_endpoint: "tonyebel.com", dns_domain: "tonyebel.com", dns_record_id: "21861902" }
            - { dns_endpoint: "cooperjosh.com", dns_domain: "cooperjosh.com", dns_record_id: "51917868" }
            - { dns_endpoint: "thesandlotkc.com", dns_domain: "thesandlotkc.com", dns_record_id: "1771663619" }
        chadpi:
          dns_records:
            - { dns_endpoint: "chad.tonyebel.com", dns_domain: "tonyebel.com", dns_record_id: "1787676262" }
