---
all:
  hosts:
    probook:
      ansible_host: 127.0.0.1
      ansible_port: 9010
    tcachy:
      ansible_host: 192.168.1.80
  children:
    common:
      hosts:
        probook:
        tcachy:
    developer:
      hosts:
        probook:
        tcachy:
    work:
      hosts:
        probook:
    connect:
      hosts:
        probook:
          listen_port: 9010
          enabled: false
